SET NAMES utf8mb4;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS vocab;
CREATE SCHEMA vocab;
USE vocab;

CREATE TABLE vocab (
	vocab_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    word VARCHAR(45) NOT NULL,
    word_definition VARCHAR(255) NOT NULL,
    category VARCHAR(45) NOT NULL
    )
    
    